### ISSUE TITLE
Readme suggestion

### ISSUE THREAD

**Issue by gilbertohasnofb** [sylhare/nprime#17]
First of all, thanks for the library. I would like to suggest the addition of small code snippets in the `README.md` file as a small form of documentation of the functions available. For instance, adding that one can import the Miller-Rabin algorithm using `from nprime.pyprime import miller_rabin` could be a time saver for the users.

**Comment by sylhare** [comment]
Ah Indeed!

Good suggestion, I will add a couple of lines for how to use the algorithms.
Let me know if you find any bug while using it 😉

**Comment by gilbertohasnofb** [comment]
> Let me know if you find any bug while using it wink

Definitely! These algorithms are quite handy when solving Project Euler problems :smile:

**Comment by sylhare** [comment]
Et voilà, let me know if it should be better.

**Comment by gilbertohasnofb** [comment]
That's much better, thanks a lot!
