### ISSUE TITLE
"Sieve" functions are actually doing trial division

### ISSUE THREAD

**Issue by FrozenBob** [sylhare/nprime#20]
generate_primes and sieve_eratosthenes are supposed to be using the Sieve of Eratosthenes, but they're actually doing trial division. They would be much faster with an actual sieve, which has much better time complexity.

**Comment by sylhare** [comment]
🤔 

I will have to take another look to [Sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes) and [Trial Division](https://en.wikipedia.org/wiki/Trial_division).

Thanks!

**Comment by sylhare** [comment]
The `generate_primes` method seems closer to the sieve it seems. I'll see how I'll work that out.

**Comment by sylhare** [comment]
So I kept the previous one and renamed it `trial division` and added a new one that is the sieve one instead.
