### ISSUE TITLE
Don't import pyplot as a top-level import.

### ISSUE THREAD

**Issue by Erotemic** [sylhare/nprime#21]
Importing the matplotlib.pyplot module has side-effects (such as preventing the user from changing the mpl backend without potential issues). It would be better practice if the `plt` imports were done locally in the functions that used them.  

IMHO it would be even better to factor the plotting functions in to a separate submodule: `nprime.plots` or something like that. 

Otherwise, nice package :smile:. Having a nice home for prime finding/testing algorithms is something pypi definitely needs!

**Comment by sylhare** [comment]
Thanks I'll see what you wrote.
Great feedbacks 👍

**Comment by sylhare** [comment]
I put in a plot file, and with the submodule logic, it should be all fine
