### ISSUE TITLE
Expose primary function in a top-level API 

### ISSUE THREAD

**Issue by Erotemic** [sylhare/nprime#22]
It would be nice if I could just `import nprime` and use `nprime.is_prime` etc.. or some other `nprime.sieve_eratosthenes`, etc... 

Naively, many package terminates might accomplish this by adding the following to `__init__.py`:

```python
from nprime import *
```

But in general I find `import *` to be bad practice, and I'd prefer a more explicit set of imports. Fortunately, one of my packages [mkinit](https://github.com/Erotemic/mkinit) can accomplish this. First installing `pip install mkinit` and then running `mkinit nprime/__init__.py -w` will updat the `__init__.py` file with autogenerated text as follows:

```python
from nprime import pyprime
from nprime import toolbox

from nprime.pyprime import (fermat, find_primes, generate_primes, is_prime,
                            miller_rabin, pyprime, sacks, sacks_plot,
                            sieve_eratosthenes, trial_division, ulam,
                            ulam_plot,)
from nprime.toolbox import (HERE, convert, crypto_random, read_advance,
                            read_into_lines_list, read_with_codecs, save,
                            timex,)

__all__ = ['HERE', 'convert', 'crypto_random', 'fermat', 'find_primes',
           'generate_primes', 'is_prime', 'miller_rabin', 'pyprime', 'pyprime',
           'read_advance', 'read_into_lines_list', 'read_with_codecs', 'sacks',
           'sacks_plot', 'save', 'sieve_eratosthenes', 'timex', 'toolbox',
           'trial_division', 'ulam', 'ulam_plot']
```

However, we probably only want to include the `pyprime` functions in the top-level API. The utility functions are something that users of this package will likely not want to be distracted by, so we can modify the `__init__.py` file to add the `__submodules__ = ['pyprime']` attribute, which lets `mkinit` know that we only care about certain submodules.  

This results in a slightly cleaner: 

```python
"""
nprime main application folder

mkinit nprime/__init__.py -w
"""

__submodules__ = [
    'pyprime',
]
from nprime import pyprime

from nprime.pyprime import (fermat, find_primes, generate_primes, is_prime,
                            miller_rabin, pyprime, sacks, sacks_plot,
                            sieve_eratosthenes, trial_division, ulam,
                            ulam_plot,)

__all__ = ['fermat', 'find_primes', 'generate_primes', 'is_prime',
           'miller_rabin', 'pyprime', 'pyprime', 'sacks', 'sacks_plot',
           'sieve_eratosthenes', 'trial_division', 'ulam', 'ulam_plot']
```

However, as I mentioned in #21, I'd like to see the plotting functions factored into a separate submodule. If that was done the final `__init__.py` file should look like this:

```python
"""
The nprime module

Autogenerate Command:
    mkinit nprime/__init__.py -w
"""

__submodules__ = [
    'pyprime',
]
from nprime import pyprime

from nprime.pyprime import (fermat, find_primes, generate_primes, is_prime,
                            miller_rabin, sacks, sieve_eratosthenes,
                            trial_division, ulam,)

__all__ = ['fermat', 'find_primes', 'generate_primes', 'is_prime',
           'miller_rabin', 'pyprime', 'sacks',
           'sieve_eratosthenes', 'trial_division', 'ulam']
```

**Comment by sylhare** [comment]
I'll take a look thanks :)

**Comment by sylhare** [comment]
That's quite a neat trick now that I look at it, creating a submodule and the import.

**Comment by sylhare** [comment]
All done! 👍
