### ISSUE TITLE
Add `__version__` to `__init__.py`

### ISSUE THREAD

**Issue by Erotemic** [sylhare/nprime#23]
It is customary for top-level packages to have a `__version__` attribute. 

Currently you define version='1.1.1' in setup.py. What would be better is if you defined 

```python
__version__ = '1.1.1'
```
in `__init__.py` and then in setup.py imported nprime and set `version=nprime.__version__`.

**Comment by sylhare** [comment]
Hi, thanks.

There are a lot of issues open today 😅 the project is open to contribution if you wish.
Otherwise, I'll be able to work on it later.

**Comment by sylhare** [comment]
Fixed this one 👍
