### ISSUE TITLE
Reclaiming names on pypi

### ISSUE THREAD

**Issue by Erotemic** [sylhare/nprime#24]
I noticed that you had recently renamed `pyprime` to `nprime` because of conflicts on pypi. 

Just so you are aware, there is a process for reclaiming names (https://pypi.org/help/#project-name-claim)  if an existing project is unused / unmaintained. Its possible the the authors of the `pyprime` or `prime` module might relinquish the module name if you ask. They don't look highly used.

**Comment by sylhare** [comment]
Allo, what is this one about?

**Comment by Erotemic** [comment]
Hit submit too soon, sry.

**Comment by sylhare** [comment]
Ah I see thanks, I didn't know that.
Should I rename the package though? I kinda liked pyprime at first but then I found nprime was ok. 🤷 

I'll look into it, I wouldn't want people using the package to be lost if it suddenly gets changed 🤔

**Comment by Erotemic** [comment]
If you currently have a lot of users, its best to not make breaking changes. However, I do agree that `pyprime` sounds nicer. It is possible to host the same package under two names, raise a deprecation warning for one name, and point to the new name. That's generally the best way to handle a name-switch if the package is used. However, if there are just a few users it isn't to hard to contact them and give them a heads up. 

Ultimately, its up to you if you want to pursue a name change or if you are happy with `nprime`. I think its a fine name, but I do agree `pyprime` sounds nicer. I just saw your note that "pyprime is dead", so I wanted to make sure you knew that there is a process to reclaim the name if you really want it. 

What's the motivation behind the `n` in `nprime`? Is it just `n` for number?

**Comment by sylhare** [comment]
Yeah it's for n number 😅 
Let's say I don't think there is a massive amount of people using the package. I'll go check out for pyprime ;)

**Comment by sylhare** [comment]
Because I see two:

- https://pypi.org/project/pyprimes/ that says "Generate and test for prime numbers." but seems abandoned
- https://pypi.org/project/pyprime/ that says "Base module for accessing Cisco PI API" which is totally not about primes 

And Pypi don't remove projects solely because they are abandoned. With pyprimes and pyprime, you always have the risk of getting confused for the other abandoned one. 🤔

**Comment by Erotemic** [comment]
That's fair, maybe its best left as nprime.
